### ISSUE TITLE
... 1 ...

### ISSUE THREAD

**Issue by vichejo** [wesnolte/Pajinate#1]
Hello, thank you very much for this wonderful jquery!
I set on my page but I detect an error, not if due to a misconfiguration on my part or is it really a mistake.
The bar numbers of pages initially I get the'...' front and behind the numbers whether or not they have more pages (<<<... 1 ...>>>). Then, clicking on the numbers or <<<>>> the situation corrects itself.
Greetings.

**Comment by wesnolte** [comment]
Do you have sample code that you can point me to?

**Comment by vichejo** [comment]
Hello, yes! this is a web in development: devel2.coberture.com
Thanks you!

**Comment by wesnolte** [comment]
I think you're right and it may be a bug. Unfortunately I won't have time to fix it for a few weeks. Feel free to fork the project and fix the bug if I don't get there before you. 

Thanks for letting me know.

**Comment by wesnolte** [comment]
Pull the code from github again, there was an update yesterday that may fix your problem.

**Comment by vichejo** [comment]
ok, thank you! I'll try the code again and I mention the results!
Thank you very much again for your effort.
