### ISSUE TITLE
Ajax integration

### ISSUE THREAD

**Issue by eweap** [wesnolte/Pajinate#14]
Hello!
Is there a way to avoid having to restart the "pajinate" after injecting the contents by ajax for pagination?

Thank you for your work !
Regards.

**Comment by wesnolte** [comment]
There's a guy that's done some ajax stuff here: https://github.com/slavick/Pajinate I'm trying to convince him to let me pull the change in :)

**Comment by eweap** [comment]
Oh ! great news, thanks !
