### ISSUE TITLE
YUI Compressor thinks "goto" is a reserved word

### ISSUE THREAD

**Issue by rocky76** [wesnolte/Pajinate#18]
I couldn't get YUI Compressor to compress my modified version of your Pajinate plugin, it kept spitting out "identifier is a reserved word" errors. Finally tracked it down to "goto" is a reserved word in Java, which YUI Compressor is written in. So obscure, but I ended up changing every goto() to gotoNum(). 

http://www.refresh-sf.com/yui/
http://developer.yahoo.com/yui/compressor/#work
http://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html

**Comment by wesnolte** [comment]
Thanks for the feedback, I vaguely remember this issue some time back and not having time to fix it. This is sorted now.
