### ISSUE TITLE
Make the pagination scalable

### ISSUE THREAD

**Issue by xzigraz** [wesnolte/Pajinate#20]
Hey there,

I've been using this library for one of my projects and the issue I am having is that if there are millions of results and I am showing 10 results per page, this will write out a lot of page links first in the document, hide them all and then only show 10 of them. This is extremely poor on performance. I am trying to add some code so that it only write 5 page links at a time and then once it reaches the end of the set, it will generate a new set and replace the old set. I am having some issue since I am not very good with js but I think this is a very useful for this library.

That's all.

Thanks.

**Comment by wesnolte** [comment]
This is a great nice to have but I won't have the time to implement such a feature in the short term. I'm happy too accept any pull requests though :)
