### ISSUE TITLE
Multiple paginator on same page

### ISSUE THREAD

**Issue by RakeshChouhan** [wesnolte/Pajinate#32]
In my application I am using 2 paginator in same page with default configuration 
$('#global-faq-container').pajinate({
        nav_label_first : '<<',
        nav_label_last : '>>',
        nav_label_prev : '<',
        nav_label_next : '>',
        num_page_links_to_display : 5,
        items_per_page : 5,
        wrap_around: true,
        abort_on_small_lists: true
    }).hide().fadeIn('slow');

and

$('#my-faq-container').pajinate({
        nav_label_first : '<<',
        nav_label_last : '>>',
        nav_label_prev : '<',
        nav_label_next : '>',
        num_page_links_to_display : 5,
        items_per_page : 4,
        wrap_around: true,
        abort_on_small_lists: true
    }).hide().fadeIn('slow');

when I paginate using global paginate then the my-faq paginate also changing.

I am using the latest code and still facing the same problem.

**Comment by RakeshChouhan** [comment]
I am facing this problem, please fix this issue.

**Comment by Lipdk** [comment]
Explicit loop:

$('.paginacao').each(function(){
     $(this).pajinate();
});
