### ISSUE TITLE
Give a class instead of hiding

### ISSUE THREAD

**Issue by KittyGiraudel** [wesnolte/Pajinate#38]
The main problem of hiding with .hide() is that search engine bots can't index the content, which can be pretty problematic.

I had to edit the plugin to fix the problem. Instead of directly hiding/showing items, I gave them a class to toggle. This class hides the content with CSS in order to make it indexable. 

It would be cool if you could add the option to give a class to toggle instead of hide/show. You can still leave the hide/show thing as a default value.

Thanks a lot. :)

Edit: by the way, here is the class I used.

.visually-hidden {
position: absolute;
overflow: hidden;
clip: rect(0 0 0 0);
height: 1px;
width: 1px;
margin: -1px !important;
padding: 0 !important;
border: none;
}

**Comment by wesnolte** [comment]
It probably faster your way too! Could you submit a pull request please :)
