### ISSUE TITLE
next_link on "last page" stays

### ISSUE THREAD

**Issue by FlashJunior** [wesnolte/Pajinate#8]
If you'r on page 1 and click on "previous_link" -> it goes to last page.

But if you'r at the last page and i click on "next_link" -> it stays.

one of theme is rong or should be fixed :-)

**Comment by wesnolte** [comment]
Looks like it's working? Have a look at the last example (bottom right)

http://dl.dropbox.com/u/4151695/html/pajinate/examples/example1.html

**Comment by FlashJunior** [comment]
yes. all of theme have the problem.

click on "next_link" you stay always @ last page.
but if you click on "previous_link" you can click endless thru all pages.

**Comment by wesnolte** [comment]
The only theme that wraps should be the last one. You found a bug but the last one is working correctly. The others shouldn't be wrapping at all but are wrapping left so they all have a bug. I'll fix that bug. To enable wrapping you need to use the "wrap_around" option. It defaults to false.

**Comment by FlashJunior** [comment]
ok.

**Comment by wesnolte** [comment]
Okay bug fixed and committed. Note that wrapping is off by default.

**Comment by FlashJunior** [comment]
thx, perfect!
