### ISSUE TITLE
not work on multiple instance and class selector

### ISSUE THREAD

**Issue by mkdgs** [wesnolte/Pajinate#9]
pajinate not work on multiple instance when a class selector is used instead of an id (pagination work only with the last  container element)

i had solved this problem for my use, take a look:
https://github.com/m-d/Pajinate/blob/master/jquery.pajinate.js

**Comment by wesnolte** [comment]
Hi, it was never meant to work with class selectors although I don't mind the code being changed to work with ids and classes. You're change unfortunately doesn't do both safely.
